# NumPy Fundamentals

In [1]:
import numpy as np

## Indexing

In [2]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
array_a[0] = [10,20,30]
array_a

array([[10, 20, 30],
       [ 4,  5,  6]])

In [6]:
array_a[1] = [40,50,60]
array_a

array([[10, 20, 30],
       [40, 50, 60]])

### Specific Values

In [7]:
array_a[0][1]

20

In [13]:
if array_a[0][1] == 20:
    array_a[0][1] = 200 
   
   

In [14]:
array_a

array([[ 10, 200,  30],
       [ 40,  50,  60]])

In [15]:
array_a[0,1]

200

In [17]:
array_a[:, 0]

array([10, 40])

### Negative Indices

In [16]:
array_a[-1]

array([40, 50, 60])

In [18]:
if 60 in array_a[-1]:
    print("60 is in array_a")
else:
    print("no such number was found")

60 is in array_a


In [23]:
array_a[-1].append([[70, 80, 90]])
array_a

AttributeError: 'numpy.ndarray' object has no attribute 'append'

## Assigning Values

In [24]:
array_a = np.array([[1,2,3], [4,5,6], [7,8,9]])
array_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
array_a[0, 2]

3

In [30]:
array_a[0,2] = 3
array_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
array_a[0] = 10, 20, 30
array_a

array([[10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [35]:
array_a[1] = 40, 50, 60
array_a

array([[10, 20, 30],
       [40, 50, 60],
       [ 7,  8,  9]])

In [36]:
array_a[2] = 70, 80, 90
array_a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [39]:

array_a[:, 2]

array([30, 60, 90])

In [40]:
array_a[0, :]

array([10, 20, 30])

In [41]:
list_a = [100, 200, 300]
array_a[0] = list_a
array_a

array([[100, 200, 300],
       [ 40,  50,  60],
       [ 70,  80,  90]])

In [42]:
list_b = [400, 500, 600]
array_a[1] = list_b
array_a

array([[100, 200, 300],
       [400, 500, 600],
       [ 70,  80,  90]])

In [43]:
list_c = [700, 800, 900]
array_a[2] = list_c
array_a

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

In [44]:
type(array_a[0])

numpy.ndarray

## Elementwise Properties

In [48]:
array_x = np.array([1,2,3])
array_x

array([1, 2, 3])

In [49]:
array_y = np.array([[4,5,6], [7,8,9]])
array_y

array([[4, 5, 6],
       [7, 8, 9]])

In [52]:
array_x + 2

array([3, 4, 5])

In [53]:
array_y ** 2

array([[16, 25, 36],
       [49, 64, 81]])

In [54]:
array_y

array([[4, 5, 6],
       [7, 8, 9]])

In [55]:
array_x ** 3

array([ 1,  8, 27])

In [56]:
array_x

array([1, 2, 3])

In [58]:
array_y

array([[4, 5, 6],
       [7, 8, 9]])

In [57]:
array_x + array_y

array([[ 5,  7,  9],
       [ 8, 10, 12]])

In [59]:
sum(array_y)

array([11, 13, 15])

In [60]:
len(array_y)

2

In [61]:
len(array_x)

3

In [65]:
array_x[0]

1

In [67]:
array_y[0, 1]

5

In [72]:
if array_x[0] < array_y[0, 1]:
    print(True)
else:
    print(False)

True


## Types of Data Supported by NumPy

In [73]:
array_a = np.array([[10,20,30], [40, 50, 60]])
array_a

array([[10, 20, 30],
       [40, 50, 60]])

In [75]:
array_a = np.array([[10,20,30], [40, 50, 60]], dtype = "float32")
array_a

array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)

In [78]:
array_a = np.array([[10,20,30], [40, 50, 60]], dtype = np.float16)
array_a

array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float16)

In [79]:
array_a = np.array([[10,20,30], [40, 50, 60]], dtype = np.complex64)
array_a

array([[10.+0.j, 20.+0.j, 30.+0.j],
       [40.+0.j, 50.+0.j, 60.+0.j]], dtype=complex64)

In [80]:
array_a = np.array([[10,20,30], [40, 50, 60]], dtype = np.bool)
array_a

<ipython-input-80-de3c4878871a>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_a = np.array([[10,20,30], [40, 50, 60]], dtype = np.bool)


array([[ True,  True,  True],
       [ True,  True,  True]])

In [81]:
array_a = np.array([[10,20,30], [40, 50, 60]], dtype = bool)
array_a

array([[ True,  True,  True],
       [ True,  True,  True]])

In [83]:
array_a = np.array([[10,20,30], [40, 50, 60]], dtype = str)
array_a

array([['10', '20', '30'],
       ['40', '50', '60']], dtype='<U2')

https://numpy.org/devdocs/reference/generated/numpy.dtype.kind.html <- <i> A link to the documentation explaining the unicode abbreviation.

## Characteristics of NumPy Functions

### Universal Functions

https://numpy.org/devdocs/reference/ufuncs.html <- <i> A link to the documentation page on Universal Functions

### Broadcasting

In [84]:
array_1 = np.array([1,2,3])
array_1

array([1, 2, 3])

In [85]:
array_2 = np.array([[1], [2]])
array_2

array([[1],
       [2]])

In [86]:
matrix_3 = np.array([[1,2,3], [4,5,6]])
matrix_3

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
np.add(array_1, matrix_3)

array([[2, 4, 6],
       [5, 7, 9]])

In [88]:
np.add(array_2, matrix_3)

array([[2, 3, 4],
       [6, 7, 8]])

### Type Casting

In [89]:
np.add(array_2, matrix_3, dtype=np.float64)

array([[2., 3., 4.],
       [6., 7., 8.]])

### Running over an Axis

In [90]:
np.mean(matrix_3, axis=0)

array([2.5, 3.5, 4.5])

In [91]:
matrix_3

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
np.mean(array_1, axis=0)

2.0

In [95]:
array_1

array([1, 2, 3])