# Generating Data w/ Numpy

In [1]:
import numpy as np

### np.empty(), np.zeros(), np.ones(), np.full()

In [3]:
array_empty = np.empty(shape = (2,3))
array_empty

array([[-1.72723371e-077, -1.73059644e-077,  1.48219694e-323],
       [ 0.00000000e+000,  0.00000000e+000,  4.17201348e-309]])

In [7]:
array_zero = np.zeros(shape=(2,3), dtype=np.int8)
array_zero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [5]:
array_ones = np.ones(shape=(2,3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
array_full = np.full(shape=(2,3), fill_value = 10**2)
array_full

array([[100, 100, 100],
       [100, 100, 100]])

In [15]:
array_full = np.full(shape=(2,3), fill_value = 10%3)
array_full

array([[1, 1, 1],
       [1, 1, 1]])

### "_like" functions

In [16]:
matrix_a = np.array([[0,9,8,7,6], [1,2,3,4,5], [100,200,300,400,500]])
matrix_a

array([[  0,   9,   8,   7,   6],
       [  1,   2,   3,   4,   5],
       [100, 200, 300, 400, 500]])

In [20]:
array_empty_like = np.empty_like(matrix_a)
array_empty_like

array([[-5764607523034234880,  5764616291030196559,                    8,
                           0,                    0],
       [                   0,                    0,                    0,
                           0,                    0],
       [                   0,                    0,                    0,
                           0, -8070441764252009001]])

In [21]:
 array_zero_like = np.zeros_like(matrix_a)
array_zero_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
type(array_empty_like)

numpy.ndarray

In [23]:
type(array_zero_like)

numpy.ndarray

### np.arange()

In [25]:
range(0, 30)

range(0, 30)

In [28]:
print(list(range(30)), end=" ")

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] 

In [31]:
array_range = np.arange(25)
array_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
array_range = np.arange(start=0, step=2.5, stop=30)
array_range

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

In [38]:
array_range = np.arange(start=0, step=2.5, stop=30, dtype=np.float64)
array_range

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

## Random Generators

### Defining Random Generators

In [41]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [47]:
array_RG = gen(pcg())
array_RG.normal(size=(10,5))

array([[-0.98756548,  0.25254146, -0.38114765, -0.0827134 ,  0.36139958],
       [-0.9111018 , -2.3952185 ,  0.5101209 , -0.57619126, -0.97437675],
       [ 0.5267529 , -0.98626598, -1.36539179, -0.01180091, -0.07481554],
       [ 1.154781  , -1.34860893, -1.3779961 ,  1.02399782,  0.42671842],
       [ 0.32398234,  0.12860378,  0.50727847,  0.55133895, -0.02260669],
       [ 0.34894154,  1.52464205, -0.21847472, -0.32109651, -2.00925316],
       [-0.10257204,  0.42947622,  0.01834994, -0.67613413,  0.46479208],
       [ 0.16776378,  0.20703787, -0.01445907, -1.11398999, -0.49163609],
       [ 0.47432083,  0.50972094,  1.45146688,  2.63043717,  0.82388118],
       [ 0.20063138,  0.16731777,  0.07637805, -0.29913987,  0.29479226]])

In [48]:
array_RG = gen(pcg(seed=365))
array_RG.normal(size=(10,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633],
       [-0.76065577,  1.48158358,  0.01200258, -0.06846959,  0.25301664],
       [-0.52640788,  0.79613109,  0.28203421,  1.80238008,  0.93932117],
       [-0.53693283, -0.26317689, -1.77723035,  1.14900013, -2.20733915],
       [ 1.54116775, -0.5124932 , -2.14564563,  1.98878673,  0.32208907],
       [-1.2651495 ,  3.2714633 ,  1.78650493, -0.20233675,  0.20427467]])

In [52]:
array_RG.normal(size=(10,5))

array([[-1.8272256 , -0.04004098,  1.35886636, -0.22191776,  1.62415483],
       [ 0.39929258,  0.488609  ,  0.87649777, -0.35935785,  0.80067774],
       [ 1.79399017,  0.02743138, -0.84583456, -0.54593589,  2.60858047],
       [-1.70211589, -0.14530025,  2.10774715,  1.00255997, -0.5889928 ],
       [-1.3069557 , -0.48889526,  1.36111586,  2.12980876,  0.12587049],
       [-0.24186633,  0.05966318,  0.26827615, -1.4276263 ,  0.74434279],
       [ 0.59878897, -0.33562464, -0.4573883 , -1.20291155,  0.5463572 ],
       [-1.03722573, -1.42370862,  0.13170098, -0.95364036, -0.32504107],
       [ 1.64960236, -0.57607621, -1.24100132,  0.0689533 ,  0.16353889],
       [-0.98483219,  1.77028693, -0.58675716,  0.27297389, -0.10686474]])

### Generating Integers, Probabilities and Random Choices

In [58]:
array_RG = gen(pcg(seed=365))
array_RG.integers(10, size=(5,5))

array([[0, 7, 6, 7, 8],
       [6, 6, 2, 0, 6],
       [3, 0, 3, 7, 9],
       [1, 1, 8, 7, 4],
       [4, 8, 6, 4, 9]])

In [59]:
array_RG = gen(pcg(seed=365))
array_RG.integers(low=10, high=100, size=(5,5))

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]])

In [53]:
array_RG.random()

0.9359522774140308

In [60]:
array_RG = gen(pcg(seed=365))
array_RG.random(size=(5,5))

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [54]:
array_RG.random(10)

array([0.76604337, 0.18526483, 0.89886405, 0.99798368, 0.13990963,
       0.94668182, 0.85319415, 0.75612581, 0.16520904, 0.1644421 ])

In [56]:
array_RG.random((5, 10))

array([[0.1931627 , 0.30969248, 0.67085475, 0.11702466, 0.30251506,
        0.63403747, 0.27777894, 0.46940282, 0.24385814, 0.2738513 ],
       [0.93659486, 0.3946438 , 0.23648031, 0.49600233, 0.32167902,
        0.40213408, 0.04586329, 0.36740977, 0.49127422, 0.59762504],
       [0.68871296, 0.92460158, 0.83257737, 0.49310879, 0.75624296,
        0.43486246, 0.88228817, 0.46152414, 0.28197674, 0.58456864],
       [0.86571739, 0.26516498, 0.40198012, 0.15661494, 0.95552356,
        0.55567979, 0.75198454, 0.89587041, 0.73990634, 0.85393954],
       [0.00290293, 0.45982695, 0.86573241, 0.50666344, 0.12690725,
        0.10696444, 0.98741435, 0.01691933, 0.08594276, 0.85238471]])

In [62]:
array_RG = gen(pcg(seed=365))
array_RG.choice([0,1,2,3,4,5], size=(5,5))

array([[0, 4, 3, 4, 4],
       [3, 3, 1, 0, 3],
       [2, 0, 1, 4, 5],
       [0, 0, 5, 4, 2],
       [2, 4, 3, 2, 5]])

### Generating Arrays From Known Distributions

In [63]:
array_RG = gen(pcg(seed=365))
array_RG.poisson(size=(5,5))

array([[2, 0, 1, 1, 2],
       [1, 1, 0, 1, 1],
       [1, 2, 1, 1, 0],
       [0, 1, 0, 2, 1],
       [0, 1, 0, 0, 2]])

In [64]:
array_RG = gen(pcg(seed=365))
array_RG.poisson(lam=10, size=(5,5))

array([[11, 12, 12, 14, 13],
       [ 9, 10, 11, 11,  8],
       [11,  8, 10,  9, 14],
       [ 7,  8,  9, 15, 15],
       [13,  8,  8,  7,  9]])

In [67]:
array_RG = gen(pcg(seed=365))
array_RG.binomial(n = 50, p = 0.9, size=(5,5))

array([[44, 44, 44, 47, 44],
       [48, 44, 48, 42, 45],
       [43, 45, 48, 44, 46],
       [46, 45, 45, 44, 45],
       [44, 48, 44, 43, 47]])

In [68]:
array_RG = gen(pcg(seed=365))
array_RG.logistic(loc = 9, scale = 1.2, size=(5,5))

array([[10.37767822, 10.42451863,  9.63404367,  7.36153427,  9.82286787],
       [ 5.81223125, 10.09354231,  6.46790532, 11.38740256,  8.97147918],
       [10.85844698,  8.79081317,  5.962079  ,  9.99560681,  8.34539118],
       [ 7.97105522,  8.9981544 ,  8.93530194,  9.6253307 ,  9.23850869],
       [ 9.73729284,  5.3090678 , 10.13723528, 11.04372782,  7.11078651]])

https://numpy.org/doc/stable/reference/random/generator

### Applications of Random Generators

In [69]:
array_RG = gen(pcg(seed=365))

array_col_1 = array_RG.normal(loc=2, scale=3, size=(1000))
array_col_2 = array_RG.normal(loc=7, scale=2, size=(1000))
array_col_3 = array_RG.logistic(loc=11, scale=3, size=(1000))
array_col_4 = array_RG.exponential(scale=4, size=(1000))
array_col_5 = array_RG.geometric(p = 0.7, size=(1000))

In [72]:
random_test_data = np.array([array_col_1, array_col_2, array_col_3, array_col_4, array_col_5])
random_test_data

array([[ 1.59077303,  2.28243293,  1.81098674, ...,  0.1973629 ,
        -2.21015722,  2.91161235],
       [ 6.42174295,  8.57902322,  5.17270135, ...,  4.3465854 ,
         8.2176402 ,  7.90337695],
       [10.14698427, 15.93309953, -0.46878789, ...,  2.66485989,
        12.69328115, 11.79840961],
       [ 6.91500737,  6.243605  ,  2.44997251, ...,  0.80935387,
         0.50644607,  4.86816939],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         2.        ,  1.        ]])

In [73]:
random_test_data.shape

(5, 1000)

In [74]:
random_test_data = np.array([array_col_1, array_col_2, array_col_3, array_col_4, array_col_5]).transpose()
random_test_data

array([[ 1.59077303,  6.42174295, 10.14698427,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  4.86816939,  1.        ]])

In [75]:
random_test_data.shape

(1000, 5)

In [76]:
# save the results into a csv file
np.savetxt("Random-Test-Data-Numpy.csv", random_test_data, fmt="%s", delimiter=',')

In [77]:
# import the newly created csv back into python
np.genfromtxt("Random-Test-Data-Numpy.csv", delimiter=',')

array([[ 1.59077303,  6.42174295, 10.14698427,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  4.86816939,  1.        ]])