# NumPy DataTypes

In [1]:
import numpy as np

### Ndarrays

In [2]:
array_a = np.array([[10,20,30], [40,50,60]])
array_a

array([[10, 20, 30],
       [40, 50, 60]])

In [3]:
type(array_a)

numpy.ndarray

In [4]:
array_a.shape

(2, 3)

In [5]:
array_b = np.array([[100,200,300], [400, 500, 600]])
array_b

array([[100, 200, 300],
       [400, 500, 600]])

In [7]:
array_c = np.array([15])
array_c

array([15])

In [8]:
type(array_c)

numpy.ndarray

### List vs Array

In [15]:
list_a = [[1,2,3],[4,5,6]]
list_a

[[1, 2, 3], [4, 5, 6]]

In [16]:
array_a = np.array(list_a)
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
type(array_a)

numpy.ndarray

In [18]:
type(list_a)

list

In [19]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [20]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [21]:
array_a.shape

(2, 3)

In [22]:
list_a.shape

AttributeError: 'list' object has no attribute 'shape'

In [23]:
len(list_a[0])

3

In [24]:
len(list_a[1])

3

In [25]:
list_b = list_a[0] + list_a[1]


In [26]:
print(list_b)

[1, 2, 3, 4, 5, 6]


In [27]:
array_b = array_a[0] + array_a[1]
print(array_b)

[5 7 9]


In [28]:
np.sqrt(array_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [29]:
np.sqrt(list_b)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

### String vs Object vs Numbers

In [35]:
lending_co_lt = np.genfromtxt("Lending-co-LT.csv", delimiter= ',', dtype=np.int32)
lending_co_lt

array([[   -1,    -1,    -1, ...,    -1,    -1,    -1],
       [    1,    -1,    -1, ...,    -1,    -1, 16600],
       [    2,    -1,    -1, ...,    -1,    -1, 16600],
       ...,
       [ 1041,    -1,    -1, ...,    -1,    -1, 16600],
       [ 1042,    -1,    -1, ...,    -1,    -1, 15600],
       [ 1043,    -1,    -1, ...,    -1,    -1, 16600]], dtype=int32)

In [36]:
print(lending_co_lt)

[[   -1    -1    -1 ...    -1    -1    -1]
 [    1    -1    -1 ...    -1    -1 16600]
 [    2    -1    -1 ...    -1    -1 16600]
 ...
 [ 1041    -1    -1 ...    -1    -1 16600]
 [ 1042    -1    -1 ...    -1    -1 15600]
 [ 1043    -1    -1 ...    -1    -1 16600]]


In [37]:
lending_co_lt[0,0] + lending_co_lt[0,1]

-2

In [38]:
lending_co_lt = np.genfromtxt("Lending-co-LT.csv", delimiter= ',', dtype=str)
lending_co_lt

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2',
        '16600.0'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600.0'],
       ...,
       ['1041', 'id_1041', 'Product B', ..., 'Location 23', 'Region 4',
        '16600.0'],
       ['1042', 'id_1042', 'Product C', ..., 'Location 52', 'Region 6',
        '15600.0'],
       ['1043', 'id_1043', 'Product B', ..., 'Location 142', 'Region 6',
        '16600.0']], dtype='<U14')

In [40]:
lending_co_lt = np.genfromtxt("Lending-co-LT.csv", delimiter= ',', dtype=object)
lending_co_lt

array([[b'LoanID', b'StringID', b'Product', ..., b'Location', b'Region',
        b'TotalPrice'],
       [b'1', b'id_1', b'Product B', ..., b'Location 2', b'Region 2',
        b'16600.0'],
       [b'2', b'id_2', b'Product B', ..., b'Location 3', b'', b'16600.0'],
       ...,
       [b'1041', b'id_1041', b'Product B', ..., b'Location 23',
        b'Region 4', b'16600.0'],
       [b'1042', b'id_1042', b'Product C', ..., b'Location 52',
        b'Region 6', b'15600.0'],
       [b'1043', b'id_1043', b'Product B', ..., b'Location 142',
        b'Region 6', b'16600.0']], dtype=object)

In [43]:
lending_co_lt = np.genfromtxt("Lending-co-LT.csv", delimiter= ',', 
dtype = (np.int32, str, str, str, str, str, np.int32))
lending_co_lt

array([(  -1, '', '', '', '', '',    -1),
       (   1, '', '', '', '', '', 16600),
       (   2, '', '', '', '', '', 16600), ...,
       (1041, '', '', '', '', '', 16600),
       (1042, '', '', '', '', '', 15600),
       (1043, '', '', '', '', '', 16600)],
      dtype=[('f0', '<i4'), ('f1', '<U'), ('f2', '<U'), ('f3', '<U'), ('f4', '<U'), ('f5', '<U'), ('f6', '<i4')])