# Working with Arrays

### 1. Run the following cells:

In [1]:
import numpy as np

In [2]:
array_1D = np.array([10,11,12,13, 14])
array_1D

array([10, 11, 12, 13, 14])

In [3]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [4]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 2. Slice the first column of the 2-D array. 

In [6]:
array_2D[:, 0]

array([20, 43, 11])

### 3. Slice the last column of the 2-D array

In [8]:
array_2D[:, -1]

array([60, 87, 55])

### 4. Slice the second row of the 2-D array

In [10]:
array_2D[1, :]

array([43, 54, 65, 76, 87])

### 5. Slice the last two columns of the 2-nd row of the 2-D array

In [11]:
array_2D[1, -2 :]

array([76, 87])

### 6. Slice the 2-nd row of the 2-D array excluding the last two columns

### 7. Slice everything excluding the first row and last column of the 2-D array

### 8. Slice the 1st, 3rd and 5th columns of the 2-D array
   (<b>Hint</b>: Take advantage of the [start:stop:step] suntax of indices)

### 9. Slice the first columns of both matrices in the 3-D array
   (<b>Hint</b>: The syntax for the indices of the 3-D array is the following: [subarray, row, column])

### 10. Slice every other column of both matrices in the 3-D array

### 11. Use conditional slicing to check if the individual elements of each array satisfy a given condition (e.g. greater than 10)

### 12. Use conditional slicing to display which individual elements of each array satisfy this condition

### 13. Add a second condition and disaply which individual elements satisfy both (e.g. greater than 10 and odd)
   (<b>Hint</b>: Odd numbers leave a remainder of 1, when dividing by 2. Hence, we can use "%" to express this condition.)

### 13. Loosen up the requirements, so that either condition works
   (<b>Hint</b>: We just need to go from <i>condition_1</i> <b> and </b> <i>condition_2</i> to <i>condition_1</i> <b> or </b> <i>condition_2</i>)

### 14. Call the first row of the first 2-D array in the 3-D array in 3 different ways:
    A) Use precise indices for both dimensions. 
    B) Use a precise index for one dimension and a slice for the second dimension. 
    C) Uses slices (from the origin, up to the second value) for both dimensions. 

### 15. Check the shapes of the 3 different notations calling the same values

### 16. Since the last two outputs contain excess dimensions, use the squeeze function to reduce them

### 17. Now check the shapes of the reduced outputs