# Working with Arrays

In [1]:
import numpy as np

## Slicing

In [2]:
matrix_a = np.array([[10,20,30], [40,50,60]])
matrix_a

array([[10, 20, 30],
       [40, 50, 60]])

In [3]:
type(matrix_a)

numpy.ndarray

In [4]:
print(matrix_a)

[[10 20 30]
 [40 50 60]]


In [5]:
matrix_a.shape

(2, 3)

### Basic Slicing

### Stepwise Slicing

### Conditional Slicing

## Dimensions and the Squeeze Function