# Working with Arrays

In [1]:
import numpy as np

## Slicing

In [2]:
matrix_a = np.array([[10,20,30], [40,50,60]])
matrix_a

array([[10, 20, 30],
       [40, 50, 60]])

In [3]:
type(matrix_a)

numpy.ndarray

In [4]:
print(matrix_a)

[[10 20 30]
 [40 50 60]]


In [5]:
matrix_a.shape

(2, 3)

### Basic Slicing

In [6]:
matrix_a[:]

array([[10, 20, 30],
       [40, 50, 60]])

In [8]:
matrix_a[0:0]

array([], shape=(0, 3), dtype=int64)

In [9]:
matrix_a[0:1]

array([[10, 20, 30]])

In [10]:
matrix_a[0:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [11]:
matrix_a[:,:]

array([[10, 20, 30],
       [40, 50, 60]])

In [12]:
type(matrix_a)

numpy.ndarray

In [13]:
matrix_a[:1]

array([[10, 20, 30]])

In [14]:
matrix_a[1:]

array([[40, 50, 60]])

In [15]:
matrix_a[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [19]:
matrix_a[-1:]

array([[40, 50, 60]])

In [20]:
matrix_a[:,1:]

array([[20, 30],
       [50, 60]])

In [16]:
matrix_a[2:]

array([], shape=(0, 3), dtype=int64)

In [21]:
matrix_a

array([[10, 20, 30],
       [40, 50, 60]])

In [22]:
matrix_a[1:,1:]

array([[50, 60]])

### Stepwise Slicing

In [23]:
matrix_b = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
matrix_b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [39]:
# [::,::] = before the comma -> columns, after the comma -> rows
print(matrix_b[::,::])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [40]:

print(matrix_b[::2,::])


[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [41]:
print(matrix_b[::2,::2])

[[ 1  3  5]
 [11 13 15]]


In [45]:
print(matrix_b[-1::-2,::2])

[[11 13 15]
 [ 1  3  5]]


In [46]:
print(matrix_b[-1::-1,::2])

[[11 13 15]
 [ 6  8 10]
 [ 1  3  5]]


In [48]:
print(matrix_b[2::2,::2])

[[11 13 15]]


In [49]:
matrix_b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [50]:
matrix_b[::,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])

In [56]:
matrix_b[:-2:,:-2:]

array([[1, 2, 3]])

### Conditional Slicing

In [65]:
matrix_c = np.array([[1,10,12,32,56], [20,17,90,73,19], [76,33,97,12,5]])
matrix_c

array([[ 1, 10, 12, 32, 56],
       [20, 17, 90, 73, 19],
       [76, 33, 97, 12,  5]])

In [66]:
matrix_c[:, 0]

array([ 1, 20, 76])

In [67]:
matrix_c[:, 0] > 2

array([False,  True,  True])

In [68]:
matrix_c[:,:] > 2

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [73]:
matrix_c[matrix_c[:,:] >= 2]

array([10, 12, 32, 56, 20, 17, 90, 73, 19, 76, 33, 97, 12,  5])

In [77]:
matrix_c[(matrix_c[:,:] % 2 != 0) & (matrix_c[:,:] <= 40)]

array([ 1, 17, 19, 33,  5])

In [ ]:
matrix_c([matrix_c[:,:] % 2 == 0])

## Dimensions and the Squeeze Function

In [78]:
matrix_d = np.array([[10,20,30,40,50], [90,87, 54,23, 21], [100, 45, 78, 1000, 94]])
matrix_d

array([[  10,   20,   30,   40,   50],
       [  90,   87,   54,   23,   21],
       [ 100,   45,   78, 1000,   94]])

In [79]:
type(matrix_d[0,0])

numpy.int64

In [80]:
print(matrix_d[0,0])

10


In [81]:
type(matrix_d[0,0:1])

numpy.ndarray

In [82]:
print(matrix_d[0,0:1])

[10]


In [83]:
type(matrix_d[0:1,0:1])

numpy.ndarray

In [85]:
print(matrix_d[0:1,0:1])

[[10]]


In [86]:
print(matrix_d[0,0].shape) #scalar
print(matrix_d[0,0:1].shape) #vector
print(matrix_d[0:1,0:1].shape) #matrix

()
(1,)
(1, 1)


In [ ]:
# the squeeze method removes all the unnecessary dimensions of an array

In [87]:
matrix_d[0:1,0:1].squeeze()

array(10)

In [88]:
 type(matrix_d[0:1,0:1].squeeze())

numpy.ndarray

In [89]:
matrix_d[0:1,0:1].squeeze().shape

()

In [90]:
print(matrix_d[0:1,0:1].squeeze())

10


In [91]:
np.squeeze(matrix_d[0:1,0:1])

array(10)

In [92]:
print(matrix_d[0,0].squeeze().shape) #scalar
print(matrix_d[0,0:1].squeeze().shape) #vector
print(matrix_d[0:1,0:1].squeeze().shape) #matrix

()
()
()
